enableImmutableInstalls: false

nodeLinker: node-modules

npmAuthToken: "${GITHUB_TOKEN}"

npmScopes:
  crashdump:
    npmPublishRegistry: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
