// The length of the radix in bits.
export const RADIX_BITS = 10;

// The length of the random identifier in bits.
export const ID_BITS_LENGTH = 15;

// The length of the iteration exponent in bits.
export const ITERATION_EXP_BITS_LENGTH = 4;

// The length of the extendable backup flag in bits.
export const EXTENDABLE_BACKUP_FLAG_BITS_LENGTH = 1;

// The length of the random identifier, extendable backup flag and iteration exponent in words.
export const ITERATION_EXP_WORDS_LENGTH = Math.floor(
  (ID_BITS_LENGTH +
    EXTENDABLE_BACKUP_FLAG_BITS_LENGTH +
    ITERATION_EXP_BITS_LENGTH +
    RADIX_BITS -
    1) /
    RADIX_BITS,
);

// The maximum iteration exponent
export const MAX_ITERATION_EXP = 2 ** ITERATION_EXP_BITS_LENGTH;

// The maximum number of shares that can be created.
export const MAX_SHARE_COUNT = 16;

// The length of the RS1024 checksum in words.
export const CHECKSUM_WORDS_LENGTH = 3;

// The length of the digest of the shared secret in bytes.
export const DIGEST_LENGTH = 4;

// The customization string used in the RS1024 checksum and in the PBKDF2 salt when the extendable backup flag is not set.
export const CUSTOMIZATION_STRING_NON_EXTENDABLE = "shamir";

// The customization string used in RS1024 checksum when the extendable backup flag is set.
export const CUSTOMIZATION_STRING_EXTENDABLE = "shamir_extendable";

// The minimum allowed entropy of the master secret.
export const MIN_ENTROPY_BITS = 128;

// The minimum allowed length of the mnemonic in words.
export const METADATA_WORDS_LENGTH =
  ITERATION_EXP_WORDS_LENGTH + 2 + CHECKSUM_WORDS_LENGTH;

// The length of the mnemonic in words without the share value.
export const MNEMONICS_WORDS_LENGTH = Math.floor(
  METADATA_WORDS_LENGTH + (MIN_ENTROPY_BITS + RADIX_BITS - 1) / RADIX_BITS,
);

// The minimum number of iterations to use in PBKDF2.
export const ITERATION_COUNT = 10000;

// The number of rounds to use in the Feistel cipher.
export const ROUND_COUNT = 4;

// The index of the share containing the digest of the shared secret.
export const DIGEST_INDEX = 254;

// The index of the share containing the shared secret.
export const SECRET_INDEX = 255;

// The precomputed exponent and log tables.
// ```
//    const exp = List<int>.filled(255, 0)
//    const log = List<int>.filled(256, 0)
//    const poly = 1
//
//    for (let i = 0; i < exp.length; i++) {
//      exp[i] = poly
//      log[poly] = i
//      // Multiply poly by the polynomial x + 1.
//      poly = (poly << 1) ^ poly
//      // Reduce poly by x^8 + x^4 + x^3 + x + 1.
//      if (poly & 0x100 === 0x100) poly ^= 0x11B
//   }
// ```
export const EXP_TABLE = [
  1, 3, 5, 15, 17, 51, 85, 255, 26, 46, 114, 150, 161, 248, 19, 53, 95, 225, 56,
  72, 216, 115, 149, 164, 247, 2, 6, 10, 30, 34, 102, 170, 229, 52, 92, 228, 55,
  89, 235, 38, 106, 190, 217, 112, 144, 171, 230, 49, 83, 245, 4, 12, 20, 60,
  68, 204, 79, 209, 104, 184, 211, 110, 178, 205, 76, 212, 103, 169, 224, 59,
  77, 215, 98, 166, 241, 8, 24, 40, 120, 136, 131, 158, 185, 208, 107, 189, 220,
  127, 129, 152, 179, 206, 73, 219, 118, 154, 181, 196, 87, 249, 16, 48, 80,
  240, 11, 29, 39, 105, 187, 214, 97, 163, 254, 25, 43, 125, 135, 146, 173, 236,
  47, 113, 147, 174, 233, 32, 96, 160, 251, 22, 58, 78, 210, 109, 183, 194, 93,
  231, 50, 86, 250, 21, 63, 65, 195, 94, 226, 61, 71, 201, 64, 192, 91, 237, 44,
  116, 156, 191, 218, 117, 159, 186, 213, 100, 172, 239, 42, 126, 130, 157, 188,
  223, 122, 142, 137, 128, 155, 182, 193, 88, 232, 35, 101, 175, 234, 37, 111,
  177, 200, 67, 197, 84, 252, 31, 33, 99, 165, 244, 7, 9, 27, 45, 119, 153, 176,
  203, 70, 202, 69, 207, 74, 222, 121, 139, 134, 145, 168, 227, 62, 66, 198, 81,
  243, 14, 18, 54, 90, 238, 41, 123, 141, 140, 143, 138, 133, 148, 167, 242, 13,
  23, 57, 75, 221, 124, 132, 151, 162, 253, 28, 36, 108, 180, 199, 82, 246,
];
export const LOG_TABLE = [
  0, 0, 25, 1, 50, 2, 26, 198, 75, 199, 27, 104, 51, 238, 223, 3, 100, 4, 224,
  14, 52, 141, 129, 239, 76, 113, 8, 200, 248, 105, 28, 193, 125, 194, 29, 181,
  249, 185, 39, 106, 77, 228, 166, 114, 154, 201, 9, 120, 101, 47, 138, 5, 33,
  15, 225, 36, 18, 240, 130, 69, 53, 147, 218, 142, 150, 143, 219, 189, 54, 208,
  206, 148, 19, 92, 210, 241, 64, 70, 131, 56, 102, 221, 253, 48, 191, 6, 139,
  98, 179, 37, 226, 152, 34, 136, 145, 16, 126, 110, 72, 195, 163, 182, 30, 66,
  58, 107, 40, 84, 250, 133, 61, 186, 43, 121, 10, 21, 155, 159, 94, 202, 78,
  212, 172, 229, 243, 115, 167, 87, 175, 88, 168, 80, 244, 234, 214, 116, 79,
  174, 233, 213, 231, 230, 173, 232, 44, 215, 117, 122, 235, 22, 11, 245, 89,
  203, 95, 176, 156, 169, 81, 160, 127, 12, 246, 111, 23, 196, 73, 236, 216, 67,
  31, 45, 164, 118, 123, 183, 204, 187, 62, 90, 251, 96, 177, 134, 59, 82, 161,
  108, 170, 85, 41, 157, 151, 178, 135, 144, 97, 190, 220, 252, 188, 149, 207,
  205, 55, 63, 91, 209, 83, 57, 132, 60, 65, 162, 109, 71, 20, 42, 158, 93, 86,
  242, 211, 171, 68, 17, 146, 217, 35, 32, 46, 137, 180, 124, 184, 38, 119, 153,
  227, 165, 103, 74, 237, 222, 197, 49, 254, 24, 13, 99, 140, 128, 192, 247,
  112, 7,
];

//
// SLIP39 wordlist
//
export const WORD_LIST = [
  "academic",
  "acid",
  "acne",
  "acquire",
  "acrobat",
  "activity",
  "actress",
  "adapt",
  "adequate",
  "adjust",
  "admit",
  "adorn",
  "adult",
  "advance",
  "advocate",
  "afraid",
  "again",
  "agency",
  "agree",
  "aide",
  "aircraft",
  "airline",
  "airport",
  "ajar",
  "alarm",
  "album",
  "alcohol",
  "alien",
  "alive",
  "alpha",
  "already",
  "alto",
  "aluminum",
  "always",
  "amazing",
  "ambition",
  "amount",
  "amuse",
  "analysis",
  "anatomy",
  "ancestor",
  "ancient",
  "angel",
  "angry",
  "animal",
  "answer",
  "antenna",
  "anxiety",
  "apart",
  "aquatic",
  "arcade",
  "arena",
  "argue",
  "armed",
  "artist",
  "artwork",
  "aspect",
  "auction",
  "august",
  "aunt",
  "average",
  "aviation",
  "avoid",
  "award",
  "away",
  "axis",
  "axle",
  "beam",
  "beard",
  "beaver",
  "become",
  "bedroom",
  "behavior",
  "being",
  "believe",
  "belong",
  "benefit",
  "best",
  "beyond",
  "bike",
  "biology",
  "birthday",
  "bishop",
  "black",
  "blanket",
  "blessing",
  "blimp",
  "blind",
  "blue",
  "body",
  "bolt",
  "boring",
  "born",
  "both",
  "boundary",
  "bracelet",
  "branch",
  "brave",
  "breathe",
  "briefing",
  "broken",
  "brother",
  "browser",
  "bucket",
  "budget",
  "building",
  "bulb",
  "bulge",
  "bumpy",
  "bundle",
  "burden",
  "burning",
  "busy",
  "buyer",
  "cage",
  "calcium",
  "camera",
  "campus",
  "canyon",
  "capacity",
  "capital",
  "capture",
  "carbon",
  "cards",
  "careful",
  "cargo",
  "carpet",
  "carve",
  "category",
  "cause",
  "ceiling",
  "center",
  "ceramic",
  "champion",
  "change",
  "charity",
  "check",
  "chemical",
  "chest",
  "chew",
  "chubby",
  "cinema",
  "civil",
  "class",
  "clay",
  "cleanup",
  "client",
  "climate",
  "clinic",
  "clock",
  "clogs",
  "closet",
  "clothes",
  "club",
  "cluster",
  "coal",
  "coastal",
  "coding",
  "column",
  "company",
  "corner",
  "costume",
  "counter",
  "course",
  "cover",
  "cowboy",
  "cradle",
  "craft",
  "crazy",
  "credit",
  "cricket",
  "criminal",
  "crisis",
  "critical",
  "crowd",
  "crucial",
  "crunch",
  "crush",
  "crystal",
  "cubic",
  "cultural",
  "curious",
  "curly",
  "custody",
  "cylinder",
  "daisy",
  "damage",
  "dance",
  "darkness",
  "database",
  "daughter",
  "deadline",
  "deal",
  "debris",
  "debut",
  "decent",
  "decision",
  "declare",
  "decorate",
  "decrease",
  "deliver",
  "demand",
  "density",
  "deny",
  "depart",
  "depend",
  "depict",
  "deploy",
  "describe",
  "desert",
  "desire",
  "desktop",
  "destroy",
  "detailed",
  "detect",
  "device",
  "devote",
  "diagnose",
  "dictate",
  "diet",
  "dilemma",
  "diminish",
  "dining",
  "diploma",
  "disaster",
  "discuss",
  "disease",
  "dish",
  "dismiss",
  "display",
  "distance",
  "dive",
  "divorce",
  "document",
  "domain",
  "domestic",
  "dominant",
  "dough",
  "downtown",
  "dragon",
  "dramatic",
  "dream",
  "dress",
  "drift",
  "drink",
  "drove",
  "drug",
  "dryer",
  "duckling",
  "duke",
  "duration",
  "dwarf",
  "dynamic",
  "early",
  "earth",
  "easel",
  "easy",
  "echo",
  "eclipse",
  "ecology",
  "edge",
  "editor",
  "educate",
  "either",
  "elbow",
  "elder",
  "election",
  "elegant",
  "element",
  "elephant",
  "elevator",
  "elite",
  "else",
  "email",
  "emerald",
  "emission",
  "emperor",
  "emphasis",
  "employer",
  "empty",
  "ending",
  "endless",
  "endorse",
  "enemy",
  "energy",
  "enforce",
  "engage",
  "enjoy",
  "enlarge",
  "entrance",
  "envelope",
  "envy",
  "epidemic",
  "episode",
  "equation",
  "equip",
  "eraser",
  "erode",
  "escape",
  "estate",
  "estimate",
  "evaluate",
  "evening",
  "evidence",
  "evil",
  "evoke",
  "exact",
  "example",
  "exceed",
  "exchange",
  "exclude",
  "excuse",
  "execute",
  "exercise",
  "exhaust",
  "exotic",
  "expand",
  "expect",
  "explain",
  "express",
  "extend",
  "extra",
  "eyebrow",
  "facility",
  "fact",
  "failure",
  "faint",
  "fake",
  "false",
  "family",
  "famous",
  "fancy",
  "fangs",
  "fantasy",
  "fatal",
  "fatigue",
  "favorite",
  "fawn",
  "fiber",
  "fiction",
  "filter",
  "finance",
  "findings",
  "finger",
  "firefly",
  "firm",
  "fiscal",
  "fishing",
  "fitness",
  "flame",
  "flash",
  "flavor",
  "flea",
  "flexible",
  "flip",
  "float",
  "floral",
  "fluff",
  "focus",
  "forbid",
  "force",
  "forecast",
  "forget",
  "formal",
  "fortune",
  "forward",
  "founder",
  "fraction",
  "fragment",
  "frequent",
  "freshman",
  "friar",
  "fridge",
  "friendly",
  "frost",
  "froth",
  "frozen",
  "fumes",
  "funding",
  "furl",
  "fused",
  "galaxy",
  "game",
  "garbage",
  "garden",
  "garlic",
  "gasoline",
  "gather",
  "general",
  "genius",
  "genre",
  "genuine",
  "geology",
  "gesture",
  "glad",
  "glance",
  "glasses",
  "glen",
  "glimpse",
  "goat",
  "golden",
  "graduate",
  "grant",
  "grasp",
  "gravity",
  "gray",
  "greatest",
  "grief",
  "grill",
  "grin",
  "grocery",
  "gross",
  "group",
  "grownup",
  "grumpy",
  "guard",
  "guest",
  "guilt",
  "guitar",
  "gums",
  "hairy",
  "hamster",
  "hand",
  "hanger",
  "harvest",
  "have",
  "havoc",
  "hawk",
  "hazard",
  "headset",
  "health",
  "hearing",
  "heat",
  "helpful",
  "herald",
  "herd",
  "hesitate",
  "hobo",
  "holiday",
  "holy",
  "home",
  "hormone",
  "hospital",
  "hour",
  "huge",
  "human",
  "humidity",
  "hunting",
  "husband",
  "hush",
  "husky",
  "hybrid",
  "idea",
  "identify",
  "idle",
  "image",
  "impact",
  "imply",
  "improve",
  "impulse",
  "include",
  "income",
  "increase",
  "index",
  "indicate",
  "industry",
  "infant",
  "inform",
  "inherit",
  "injury",
  "inmate",
  "insect",
  "inside",
  "install",
  "intend",
  "intimate",
  "invasion",
  "involve",
  "iris",
  "island",
  "isolate",
  "item",
  "ivory",
  "jacket",
  "jerky",
  "jewelry",
  "join",
  "judicial",
  "juice",
  "jump",
  "junction",
  "junior",
  "junk",
  "jury",
  "justice",
  "kernel",
  "keyboard",
  "kidney",
  "kind",
  "kitchen",
  "knife",
  "knit",
  "laden",
  "ladle",
  "ladybug",
  "lair",
  "lamp",
  "language",
  "large",
  "laser",
  "laundry",
  "lawsuit",
  "leader",
  "leaf",
  "learn",
  "leaves",
  "lecture",
  "legal",
  "legend",
  "legs",
  "lend",
  "length",
  "level",
  "liberty",
  "library",
  "license",
  "lift",
  "likely",
  "lilac",
  "lily",
  "lips",
  "liquid",
  "listen",
  "literary",
  "living",
  "lizard",
  "loan",
  "lobe",
  "location",
  "losing",
  "loud",
  "loyalty",
  "luck",
  "lunar",
  "lunch",
  "lungs",
  "luxury",
  "lying",
  "lyrics",
  "machine",
  "magazine",
  "maiden",
  "mailman",
  "main",
  "makeup",
  "making",
  "mama",
  "manager",
  "mandate",
  "mansion",
  "manual",
  "marathon",
  "march",
  "market",
  "marvel",
  "mason",
  "material",
  "math",
  "maximum",
  "mayor",
  "meaning",
  "medal",
  "medical",
  "member",
  "memory",
  "mental",
  "merchant",
  "merit",
  "method",
  "metric",
  "midst",
  "mild",
  "military",
  "mineral",
  "minister",
  "miracle",
  "mixed",
  "mixture",
  "mobile",
  "modern",
  "modify",
  "moisture",
  "moment",
  "morning",
  "mortgage",
  "mother",
  "mountain",
  "mouse",
  "move",
  "much",
  "mule",
  "multiple",
  "muscle",
  "museum",
  "music",
  "mustang",
  "nail",
  "national",
  "necklace",
  "negative",
  "nervous",
  "network",
  "news",
  "nuclear",
  "numb",
  "numerous",
  "nylon",
  "oasis",
  "obesity",
  "object",
  "observe",
  "obtain",
  "ocean",
  "often",
  "olympic",
  "omit",
  "oral",
  "orange",
  "orbit",
  "order",
  "ordinary",
  "organize",
  "ounce",
  "oven",
  "overall",
  "owner",
  "paces",
  "pacific",
  "package",
  "paid",
  "painting",
  "pajamas",
  "pancake",
  "pants",
  "papa",
  "paper",
  "parcel",
  "parking",
  "party",
  "patent",
  "patrol",
  "payment",
  "payroll",
  "peaceful",
  "peanut",
  "peasant",
  "pecan",
  "penalty",
  "pencil",
  "percent",
  "perfect",
  "permit",
  "petition",
  "phantom",
  "pharmacy",
  "photo",
  "phrase",
  "physics",
  "pickup",
  "picture",
  "piece",
  "pile",
  "pink",
  "pipeline",
  "pistol",
  "pitch",
  "plains",
  "plan",
  "plastic",
  "platform",
  "playoff",
  "pleasure",
  "plot",
  "plunge",
  "practice",
  "prayer",
  "preach",
  "predator",
  "pregnant",
  "premium",
  "prepare",
  "presence",
  "prevent",
  "priest",
  "primary",
  "priority",
  "prisoner",
  "privacy",
  "prize",
  "problem",
  "process",
  "profile",
  "program",
  "promise",
  "prospect",
  "provide",
  "prune",
  "public",
  "pulse",
  "pumps",
  "punish",
  "puny",
  "pupal",
  "purchase",
  "purple",
  "python",
  "quantity",
  "quarter",
  "quick",
  "quiet",
  "race",
  "racism",
  "radar",
  "railroad",
  "rainbow",
  "raisin",
  "random",
  "ranked",
  "rapids",
  "raspy",
  "reaction",
  "realize",
  "rebound",
  "rebuild",
  "recall",
  "receiver",
  "recover",
  "regret",
  "regular",
  "reject",
  "relate",
  "remember",
  "remind",
  "remove",
  "render",
  "repair",
  "repeat",
  "replace",
  "require",
  "rescue",
  "research",
  "resident",
  "response",
  "result",
  "retailer",
  "retreat",
  "reunion",
  "revenue",
  "review",
  "reward",
  "rhyme",
  "rhythm",
  "rich",
  "rival",
  "river",
  "robin",
  "rocky",
  "romantic",
  "romp",
  "roster",
  "round",
  "royal",
  "ruin",
  "ruler",
  "rumor",
  "sack",
  "safari",
  "salary",
  "salon",
  "salt",
  "satisfy",
  "satoshi",
  "saver",
  "says",
  "scandal",
  "scared",
  "scatter",
  "scene",
  "scholar",
  "science",
  "scout",
  "scramble",
  "screw",
  "script",
  "scroll",
  "seafood",
  "season",
  "secret",
  "security",
  "segment",
  "senior",
  "shadow",
  "shaft",
  "shame",
  "shaped",
  "sharp",
  "shelter",
  "sheriff",
  "short",
  "should",
  "shrimp",
  "sidewalk",
  "silent",
  "silver",
  "similar",
  "simple",
  "single",
  "sister",
  "skin",
  "skunk",
  "slap",
  "slavery",
  "sled",
  "slice",
  "slim",
  "slow",
  "slush",
  "smart",
  "smear",
  "smell",
  "smirk",
  "smith",
  "smoking",
  "smug",
  "snake",
  "snapshot",
  "sniff",
  "society",
  "software",
  "soldier",
  "solution",
  "soul",
  "source",
  "space",
  "spark",
  "speak",
  "species",
  "spelling",
  "spend",
  "spew",
  "spider",
  "spill",
  "spine",
  "spirit",
  "spit",
  "spray",
  "sprinkle",
  "square",
  "squeeze",
  "stadium",
  "staff",
  "standard",
  "starting",
  "station",
  "stay",
  "steady",
  "step",
  "stick",
  "stilt",
  "story",
  "strategy",
  "strike",
  "style",
  "subject",
  "submit",
  "sugar",
  "suitable",
  "sunlight",
  "superior",
  "surface",
  "surprise",
  "survive",
  "sweater",
  "swimming",
  "swing",
  "switch",
  "symbolic",
  "sympathy",
  "syndrome",
  "system",
  "tackle",
  "tactics",
  "tadpole",
  "talent",
  "task",
  "taste",
  "taught",
  "taxi",
  "teacher",
  "teammate",
  "teaspoon",
  "temple",
  "tenant",
  "tendency",
  "tension",
  "terminal",
  "testify",
  "texture",
  "thank",
  "that",
  "theater",
  "theory",
  "therapy",
  "thorn",
  "threaten",
  "thumb",
  "thunder",
  "ticket",
  "tidy",
  "timber",
  "timely",
  "ting",
  "tofu",
  "together",
  "tolerate",
  "total",
  "toxic",
  "tracks",
  "traffic",
  "training",
  "transfer",
  "trash",
  "traveler",
  "treat",
  "trend",
  "trial",
  "tricycle",
  "trip",
  "triumph",
  "trouble",
  "true",
  "trust",
  "twice",
  "twin",
  "type",
  "typical",
  "ugly",
  "ultimate",
  "umbrella",
  "uncover",
  "undergo",
  "unfair",
  "unfold",
  "unhappy",
  "union",
  "universe",
  "unkind",
  "unknown",
  "unusual",
  "unwrap",
  "upgrade",
  "upstairs",
  "username",
  "usher",
  "usual",
  "valid",
  "valuable",
  "vampire",
  "vanish",
  "various",
  "vegan",
  "velvet",
  "venture",
  "verdict",
  "verify",
  "very",
  "veteran",
  "vexed",
  "victim",
  "video",
  "view",
  "vintage",
  "violence",
  "viral",
  "visitor",
  "visual",
  "vitamins",
  "vocal",
  "voice",
  "volume",
  "voter",
  "voting",
  "walnut",
  "warmth",
  "warn",
  "watch",
  "wavy",
  "wealthy",
  "weapon",
  "webcam",
  "welcome",
  "welfare",
  "western",
  "width",
  "wildlife",
  "window",
  "wine",
  "wireless",
  "wisdom",
  "withdraw",
  "wits",
  "wolf",
  "woman",
  "work",
  "worthy",
  "wrap",
  "wrist",
  "writing",
  "wrote",
  "year",
  "yelp",
  "yield",
  "yoga",
  "zero",
];

export const WORD_LIST_MAP = WORD_LIST.reduce(
  (obj: { [word: string]: number }, val, idx) => {
    obj[val] = idx;
    return obj;
  },
  {},
);
